services:
  mariage-nathan:
    image: ghcr.io/digital41/mariage_nathan:latest
    container_name: mariage-nathan
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SITE_URL=${SITE_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
    volumes:
      - mariage-data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariage.rule=Host(`mariagedvora.nathanibgui.com`)
      - traefik.http.routers.mariage.entrypoints=websecure
      - traefik.http.routers.mariage.tls.certresolver=myresolver
      - traefik.http.services.mariage.loadbalancer.server.port=3000
    networks:
      - n8n_default

volumes:
  mariage-data:

networks:
  n8n_default:
    external: true
